const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 13.99,
    img: './images/item-1.jpeg',
    desc: `A stack of our signature buttermilk pancakes simply served with butter and warm syrup. Add fresh blueberries, strawberries, bananas or chocolate chips for an additional charge`,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 18.99,
    img: './images/item-2.jpeg',
    desc: `Double burger come with fresh lettuce, tomatoes, raw onions, our famous thousand Island spread over the toasted bun, and of course, beef patties. Served with a small french fry and 1 can of pop`,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `Milk blended with banana & mint ice cream, drizzled with melted chocolate & topped with more ice cream`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 10.99,
    img: './images/item-4.jpeg',
    desc: `Two sunny side up eggs along with two slice of toasted bread. `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 15.99,
    img: './images/item-5.jpeg',
    desc: `A fried egg, thickly-cut bacon and cheddar cheese smothered over the famous single beef patty`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 7.99,
    img: './images/item-6.jpeg',
    desc: `A thick and rich oreo shake with great combination of OREO® pieces and vanilla soft serve!`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-7.jpeg',
    desc: `A sandwich layered with four pieces of crispy, sweet applewood-smoked bacon with sliced cheese and egg.`,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 18.99,
    img: './images/item-8.jpeg',
    desc: `100% fresh beef patties with american cheese and tomato. Served with french fries and 1 can of pop`,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 6.99,
    img: './images/item-9.jpeg',
    desc: `Fresh strawberry and banana, blended with creamy low fat yogurt and ice`,
  },
];
export default menu;
